{{- if and .Values.api.tls.enabled (not .Values.api.tls.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-tls" (include "harbor-scanner-trivy.fullname" .) }}
  namespace: {{ include "harbor-scanner-trivy.namespace" . }}
  labels:
    {{- include "harbor-scanner-trivy.labels" . | nindent 4 }}
  {{- with (include "harbor-scanner-trivy.annotations" (dict "root" . "local" dict)) }}
  annotations:
    {{- . | trim | nindent 4 }}
  {{- end }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.api.tls.certificate | b64enc | quote }}
  tls.key: {{ .Values.api.tls.key | b64enc | quote }}
{{- end }}
