{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "harbor-scanner-trivy.serviceAccountName" . }}
  namespace: {{ include "harbor-scanner-trivy.namespace" . }}
  labels:
    {{- include "harbor-scanner-trivy.labels" . | nindent 4 }}
  {{- with (include "harbor-scanner-trivy.annotations" (dict "root" . "local" .Values.serviceAccount.annotations)) }}
  annotations:
    {{- . | trim | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
{{- end }}
